# Docker tag structure: {perl_version}[-{httpd_version}[-{mod_perl_version}]]

on:
  push:
    branches:
      - wip

name: Build & Push

jobs:
  list-versions:
    runs-on: ubuntu-latest

    outputs:
      maxrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v2

      - id: set-matrix
        run: |
          echo "::set-output name=matrix::$(find -s */Dockerfile -exec sh -c 'basename $(dirname \{})' \; | jq -nR '{perl_version: [inputs]}')"

  build:
    needs: list-versions

    runs-on: ubuntu-latest

    strategy:
      matrix: ${{fromJson(needs.list-versions.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@master
        with:
          install: true

      - name: extract versions
        id: versions
        run: |
          httpd_version=$(cat Dockerfile | perl -ne 'print $1 if /^FROM httpd:([0-9.]+)/')
          mod_perl_version=$(cat Dockerfile | perl -ne 'print $1 if /^ENV MOD_PERL_VERSION ([0-9.]+)/')
          echo "::set-output httpd_version=$httpd_version mod_perl_version=$mod_perl_version"

      - uses: docker/build-push-action@v2
        with:
          context: ./${{matrix.perl_version}}
          tags: |
            ${{matrix.perl_version}}
            ${{matrix.perl_version}}-${{steps.versions.outputs.httpd_version}}
            ${{matrix.perl_version}}-${{steps.versions.outputs.httpd_version}}-${{steps.versions.outputs.mod_perl_version}}


