# Docker tag structure: {perl_version}[-{httpd_version}[-{mod_perl_version}]]

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

name: Build & Push

jobs:
  list-versions:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v2

      - id: set-matrix
        run: |
          echo "::set-output name=matrix::$(find */Dockerfile -exec sh -c 'basename $(dirname \{})' \; | sort | jq -nRc '{perl_version: [inputs]}')"

  build:
    needs: list-versions

    runs-on: ubuntu-latest

    strategy:
      matrix: ${{fromJson(needs.list-versions.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@master

      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            buildx-${{ runner.os }}-

      - name: Extract versions
        id: versions
        run: |
          httpd_version=$(cat Dockerfile | perl -ne 'print $1 if /^FROM httpd:([0-9.]+)/')
          mod_perl_version=$(cat Dockerfile | perl -ne 'print $1 if /^ENV MOD_PERL_VERSION ([0-9.]+)/')
          echo "::set-output name=httpd_version::$httpd_version"
          echo "::set-output name=mod_perl_version::$mod_perl_version"

      - uses: docker/build-push-action@v2
        with:
          context: ./${{matrix.perl_version}}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - uses: docker/login-action@v1
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
        with:
          context: ./${{matrix.perl_version}}
          push: true
          tags: |
            ghcr.io/motemen/mod_perl:${{matrix.perl_version}}
            ghcr.io/motemen/mod_perl:${{matrix.perl_version}}-${{steps.versions.outputs.httpd_version}}
            ghcr.io/motemen/mod_perl:${{matrix.perl_version}}-${{steps.versions.outputs.httpd_version}}-${{steps.versions.outputs.mod_perl_version}}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
